Import('*')

SimObject('myScheduler.py', sim_objects=['myScheduler'])
SimObject('InterQueue.py', sim_objects=['InterQueue'])


Source('my_scheduler.cc')
Source('inter_queue.cc')


DebugFlag('scheduler')
DebugFlag('passingTest')
DebugFlag('interQ')
DebugFlag('ALGO_NETQ_Queue')
